# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
# release/v2.9 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  ignore:
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore wrangler
  - dependency-name: "github.com/rancher/wrangler"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore wrangler v3
  - dependency-name: "github.com/rancher/wrangler/v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore huaweicloud-sdk-v3
  - dependency-name: "github.com/huaweicloud/huaweicloud-sdk-go-v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  target-branch: "release/v2.9"
# release/v2.8 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  ignore:
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore wrangler
  - dependency-name: "github.com/rancher/wrangler"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore wrangler v3
  - dependency-name: "github.com/rancher/wrangler/v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore huaweicloud-sdk-v3
  - dependency-name: "github.com/huaweicloud/huaweicloud-sdk-go-v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  target-branch: "release/v2.8"
# release/v2.7 branch
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  ignore:
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore k8s and its transitives modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - dependency-name: "go.etcd.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  # Ignore wrangler
  - dependency-name: "github.com/rancher/wrangler"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore wrangler v3
  - dependency-name: "github.com/rancher/wrangler/v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]
  # Ignore huaweicloud-sdk-v3
  - dependency-name: "github.com/huaweicloud/huaweicloud-sdk-go-v3"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  target-branch: "release/v2.7"
