apiVersion: cce.pandaria.io/v1
kind: CCEClusterConfig
metadata:
  name: "c-create"
spec:
  huaweiCredentialSecret: "cattle-global-data:cc-test-cce"
  category: "CCE"
  regionID: "cn-north-1"
  clusterID: ""
  imported: false
  name: "create-1"
  labels:
  type: "VirtualMachine"
  flavor: "cce.s1.small"
  version: "v1.23"
  description: ""
  ipv6Enable: false
  hostNetwork:
    vpcID: ""
    subnetID: ""
  containerNetwork:
    mode: "overlay_l2"
    cidr: "172.16.1.0/24"
    # cidrs:
    #   - "172.16.123.0/24"
  eniNetwork:
    subnets:
  authentication:
    mode: "rbac"
    authenticatingProxy:
      ca:
      cert:
      privateKey:
  clusterBillingMode: 0
  kubernetesSvcIPRange: "10.1.2.0/24"
  tags:
  kubeProxyMode: "iptables"
  publicAccess: false
  publicIP:
    createEIP: false
    eip:
      ipType: 5_sbgp
      bandwidth:
        chargeMode: traffic
        size: 1
        shareType: PER
  extendParam:
    clusterAZ: "cn-north-1a"
    clusterExternalIP: ""
  nodePools:
    - name: "nodepool-1"
      type: "vm"
      nodePoolID: ""
      initialNodeCount: 1
      autoscaling:
        enable: false
        minNodeCount: 0
        maxNodeCount: 0
        scaleDownCooldownTime: 0
        priority: 0
      customSecurityGroups: []
      nodeTemplate:
        flavor: "t6.large.2"
        availableZone: "random"
        operatingSystem: "EulerOS 2.9"
        sshKey: "starry-keypair"
        rootVolume:
          size: 40
          type: "SSD"
        dataVolumes:
          - size: 100
            type: "SSD"
        publicIP:
        count: 1
        billingMode: 0
        runtime: "containerd"
        extendParam:
          periodType: "month"
          periodNum: 1
          isAutoRenew: "false"
