apiVersion: cce.pandaria.io/v1
kind: CCEClusterConfig
metadata:
  name: "c-create"
spec:
  huaweiCredentialSecret: "cattle-global-data:cc-test-cce"
  category: "CCE"
  regionID: "cn-east-3"
  clusterID: ""
  imported: false
  name: "cce-test"
  labels:
  type: "VirtualMachine"
  flavor: "cce.s1.small"
  version: "v1.28"
  description: ""
  ipv6Enable: false
  hostNetwork:
    vpcID: ""
    subnetID: ""
    securityGroup: ""
  containerNetwork:
    mode: "vpc-router"
    cidr: "172.16.1.0/24"
    # cidrs:
    #   - "172.16.123.0/24"
  eniNetwork:
    subnets:
  authentication:
    mode: "rbac"
    authenticatingProxy:
      ca:
      cert:
      privateKey:
  clusterBillingMode: 0
  kubernetesSvcIPRange: "10.247.0.0/16"
  tags:
  kubeProxyMode: "iptables"
  publicAccess: false
  publicIP:
    createEIP: false
    eip:
      ipType: 5_sbgp
      bandwidth:
        chargeMode: traffic
        size: 1
        shareType: PER
  natGateway:
    enabled: false
    snatRuleEIP:
      ipType: 5_sbgp
      bandwidth:
        chargeMode: traffic
        size: 5
        shareType: PER
    existingEIPID: ""
  extendParam:
    clusterAZ: ""
    clusterExternalIP: ""
  createdNodePoolIDs: null
  nodePools:
    - name: "nodepool-1"
      type: "vm"
      nodePoolID: ""
      initialNodeCount: 0
      autoscaling:
        enable: false
        minNodeCount: 0
        maxNodeCount: 0
        scaleDownCooldownTime: 0
        priority: 0
      customSecurityGroups: []
      nodeTemplate:
        flavor: "t6.large.2"
        availableZone: "cn-east-3a"
        operatingSystem: "EulerOS 2.9"
        # Edit sshKey manually
        sshKey: "KeyPair-01"
        rootVolume:
          size: 40
          type: "SSD"
        dataVolumes:
          - size: 100
            type: "SSD"
        publicIP:
        billingMode: 0
        runtime: "containerd"
        extendParam:
          periodType: "month"
          periodNum: 1
          isAutoRenew: "false"
